#!/bin/bash

## Custom, kinda generic backup script using rsync and ssh

## Constants
SRC="/"
USER_HOME="/home/matt" ## Run as root so cant use $HOME and want to keep configs local
BACKUP_DIR="$USER_HOME/.backup"
LOG_FILE="$BACKUP_DIR/backup.log"
CONFIG_FILE="$BACKUP_DIR/backup.config"
PREV_BACKUP="$BACKUP_DIR/prevbackup.txt"
EXCLUDES_FILE="$BACKUP_DIR/excludes.txt"
KEY_FILE="$USER_HOME/.ssh/id_rsa"

EXTRA_OPTS=$1

## Error checking: make sure backup 
## conf dir exists, that there root,
## conf files exist and that theres internet
if [ ! -d $BACKUP_DIR ] ; then
	exit 1
fi

if [ "$EUID" -ne 0 ] ; then
	echo "Error: No root, exiting" >> $LOG_FILE
	exit 1
elif [ ! -f $KEY_FILE ] || [ ! -f $CONFIG_FILE ] ; then
	echo "Error: missing files, exiting" >> $LOG_FILE
	exit 1
fi

## Change to check that were on network and server is up
## TODO: make this check home network as well
wget -q --tries=10 --timeout=30 --spider -O - http://google.com > /dev/null
if [ $? -ne 0 ] ; then
	echo "No internet connection, exiting" >> $LOG_FILE
	exit 1
fi


## Perform backup
# TODO: use full timestamp instead of just date

today=`date -I` ## This will be the name of the new backup dir

## Get most recent backup name for hardlinking
## and for differential
prev_date=$(head -n 1 $PREV_BACKUP)
prev_backup="../${prev_date:-""}"       ## prev_date or blank

echo "Backup started: $today" >> $LOG_FILE

## quick and dirty config file parsing
source $CONFIG_FILE

dest="$user@$server_ip:$dest_dir/$today"
ssh="ssh -p $port -i $KEY_FILE"
opts="-aA --delete --links --partial --log-file=$LOG_FILE --exclude-from=$EXCLUDES_FILE --link-dest=$prev_backup $EXTRA_OPTS"

echo "Using command: rsync $opts -e $ssh $SRC $dest" >> $LOG_FILE

rsync $opts -e "$ssh" $SRC $dest

if [ $? -eq 0 ] ; then
	echo $today > $PREV_BACKUP
	echo "Successful backup: $today" >> $LOG_FILE
else
	echo "Backup failed: $today" >> $LOG_FILE
fi
