#!/usr/bin/perl

use utf8;
use strict;
use warnings;
use experimental 'smartmatch';

my $command = 'systemctl';
my $service = 'openvpn\@mullvad';
my @allowed_commands = qw(start stop restart status);

## Gotta be root
die 'Error: You must be root\n' if ($>);

my $input_param = shift @ARGV;
chomp $input_param;

die 'Invalid input\n' if (! $input_param || ! $input_param ~~ @allowed_commands);

my $full_command = "$command $input_param $service";
system($full_command);
